=begin
#DocuSign REST API

#The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

OpenAPI spec version: v2
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CloudStorageApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CloudStorageApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CloudStorageApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CloudStorageApi' do
    it 'should create an instact of CloudStorageApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CloudStorageApi)
    end
  end

  # unit tests for create_provider
  # Configures the redirect URL information  for one or more cloud storage providers for the specified user.
  # Configures the redirect URL information  for one or more cloud storage providers for the specified user. The redirect URL is added to the authentication URL to complete the return route.
  # @param account_id The external account number (int) or account ID Guid.
  # @param user_id The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
  # @param [Hash] opts the optional parameters
  # @option opts [CloudStorageProviders] :cloud_storage_providers 
  # @return [CloudStorageProviders]
  describe 'create_provider test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_provider
  # Deletes the user authentication information for the specified cloud storage provider.
  # Deletes the user authentication information for the specified cloud storage provider. The next time the user tries to access the cloud storage provider, they must pass normal authentication for this cloud storage provider.
  # @param account_id The external account number (int) or account ID Guid.
  # @param service_id The ID of the service to access.   Valid values are the service name (\&quot;Box\&quot;) or the numerical serviceId (\&quot;4136\&quot;).
  # @param user_id The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
  # @param [Hash] opts the optional parameters
  # @return [CloudStorageProviders]
  describe 'delete_provider test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_providers
  # Deletes the user authentication information for one or more cloud storage providers.
  # Deletes the user authentication information for one or more cloud storage providers. The next time the user tries to access the cloud storage provider, they must pass normal authentication.
  # @param account_id The external account number (int) or account ID Guid.
  # @param user_id The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
  # @param [Hash] opts the optional parameters
  # @option opts [CloudStorageProviders] :cloud_storage_providers 
  # @return [CloudStorageProviders]
  describe 'delete_providers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_provider
  # Gets the specified Cloud Storage Provider configuration for the User.
  # Retrieves the list of cloud storage providers enabled for the account and the configuration information for the user.
  # @param account_id The external account number (int) or account ID Guid.
  # @param service_id The ID of the service to access.   Valid values are the service name (\&quot;Box\&quot;) or the numerical serviceId (\&quot;4136\&quot;).
  # @param user_id The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :redirect_url  The URL the user is redirected to after the cloud storage provider authenticates the user. Using this will append the redirectUrl to the authenticationUrl.  The redirectUrl is restricted to URLs in the docusign.com or docusign.net domains.  
  # @return [CloudStorageProviders]
  describe 'get_provider test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list
  # Gets a list of all the items from the specified cloud storage provider.
  # Retrieves a list of all the items in all  the folders associated with the user from the specified cloud storage provider. You can limit the scope of the returned items by providing a comma separated list of folder IDs in the request.
  # @param account_id The external account number (int) or account ID Guid.
  # @param folder_id The ID of the folder being accessed.
  # @param service_id The ID of the service to access.   Valid values are the service name (\&quot;Box\&quot;) or the numerical serviceId (\&quot;4136\&quot;).
  # @param user_id The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cloud_storage_folder_path 
  # @option opts [String] :count An optional value that sets how many items are included in the response.   The default setting for this is 25. 
  # @option opts [String] :order An optional value that sets the direction order used to sort the item list.   Valid values are:   * asc &#x3D; ascending sort order * desc &#x3D; descending sort order 
  # @option opts [String] :order_by An optional value that sets the file attribute used to sort the item list.   Valid values are:   * modified * name  
  # @option opts [String] :search_text 
  # @option opts [String] :start_position Indicates the starting point of the first item included in the response set. It uses a 0-based index. The default setting for this is 0.  
  # @return [ExternalFolder]
  describe 'list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_folders
  # Retrieves a list of all the items in a specified folder from the specified cloud storage provider.
  # Retrieves a list of all the items in a specified folder from the specified cloud storage provider. 
  # @param account_id The external account number (int) or account ID Guid.
  # @param service_id The ID of the service to access.   Valid values are the service name (\&quot;Box\&quot;) or the numerical serviceId (\&quot;4136\&quot;).
  # @param user_id The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :cloud_storage_folder_path A comma separated list of folder IDs included in the request. 
  # @option opts [String] :count An optional value that sets how many items are included in the response.   The default setting for this is 25. 
  # @option opts [String] :order An optional value that sets the direction order used to sort the item list.   Valid values are:   * asc &#x3D; ascending sort order * desc &#x3D; descending sort order 
  # @option opts [String] :order_by An optional value that sets the file attribute used to sort the item list.   Valid values are:   * modified * name  
  # @option opts [String] :search_text 
  # @option opts [String] :start_position Indicates the starting point of the first item included in the response set. It uses a 0-based index. The default setting for this is 0.  
  # @return [ExternalFolder]
  describe 'list_folders test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_providers
  # Get the Cloud Storage Provider configuration for the specified user.
  # Retrieves the list of cloud storage providers enabled for the account and the configuration information for the user.  The {serviceId} parameter can be either the service name or serviceId.
  # @param account_id The external account number (int) or account ID Guid.
  # @param user_id The user ID of the user being accessed. Generally this is the user ID of the authenticated user, but if the authenticated user is an Admin on the account, this may be another user the Admin user is accessing.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :redirect_url  The URL the user is redirected to after the cloud storage provider authenticates the user. Using this will append the redirectUrl to the authenticationUrl.  The redirectUrl is restricted to URLs in the docusign.com or docusign.net domains.  
  # @return [CloudStorageProviders]
  describe 'list_providers test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
