=begin
#DocuSign REST API

#The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

OpenAPI spec version: v2.1
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_eSign
  # This object contains details about an envelope transfer rule.
  class EnvelopeTransferRule
    # 
    attr_accessor :carbon_copy_original_owner

    # 
    attr_accessor :enabled

    # 
    attr_accessor :envelope_transfer_rule_id

    # 
    attr_accessor :event_type

    # Information about the group that triggers the transfer.
    attr_accessor :from_group

    # Information about the user who triggers the transfer.
    attr_accessor :from_user

    # 
    attr_accessor :modified_date

    # Information about the user who last modified the envelope transfer rule.
    attr_accessor :modified_user

    # Information about the destination folder to which the envelope is transferred.
    attr_accessor :to_folder

    # Information about the user to which the envelope is transferred.
    attr_accessor :to_user

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'carbon_copy_original_owner' => :'carbonCopyOriginalOwner',
        :'enabled' => :'enabled',
        :'envelope_transfer_rule_id' => :'envelopeTransferRuleId',
        :'event_type' => :'eventType',
        :'from_group' => :'fromGroup',
        :'from_user' => :'fromUser',
        :'modified_date' => :'modifiedDate',
        :'modified_user' => :'modifiedUser',
        :'to_folder' => :'toFolder',
        :'to_user' => :'toUser'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'carbon_copy_original_owner' => :'String',
        :'enabled' => :'String',
        :'envelope_transfer_rule_id' => :'String',
        :'event_type' => :'String',
        :'from_group' => :'Group',
        :'from_user' => :'UserInformation',
        :'modified_date' => :'String',
        :'modified_user' => :'UserInformation',
        :'to_folder' => :'Folder',
        :'to_user' => :'UserInformation'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'carbonCopyOriginalOwner')
        self.carbon_copy_original_owner = attributes[:'carbonCopyOriginalOwner']
      end

      if attributes.has_key?(:'enabled')
        self.enabled = attributes[:'enabled']
      end

      if attributes.has_key?(:'envelopeTransferRuleId')
        self.envelope_transfer_rule_id = attributes[:'envelopeTransferRuleId']
      end

      if attributes.has_key?(:'eventType')
        self.event_type = attributes[:'eventType']
      end

      if attributes.has_key?(:'fromGroup')
        self.from_group = attributes[:'fromGroup']
      end

      if attributes.has_key?(:'fromUser')
        self.from_user = attributes[:'fromUser']
      end

      if attributes.has_key?(:'modifiedDate')
        self.modified_date = attributes[:'modifiedDate']
      end

      if attributes.has_key?(:'modifiedUser')
        self.modified_user = attributes[:'modifiedUser']
      end

      if attributes.has_key?(:'toFolder')
        self.to_folder = attributes[:'toFolder']
      end

      if attributes.has_key?(:'toUser')
        self.to_user = attributes[:'toUser']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          carbon_copy_original_owner == o.carbon_copy_original_owner &&
          enabled == o.enabled &&
          envelope_transfer_rule_id == o.envelope_transfer_rule_id &&
          event_type == o.event_type &&
          from_group == o.from_group &&
          from_user == o.from_user &&
          modified_date == o.modified_date &&
          modified_user == o.modified_user &&
          to_folder == o.to_folder &&
          to_user == o.to_user
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [carbon_copy_original_owner, enabled, envelope_transfer_rule_id, event_type, from_group, from_user, modified_date, modified_user, to_folder, to_user].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DocuSign_eSign.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
