=begin
#DocuSign REST API

#The DocuSign REST API provides you with a powerful, convenient, and simple Web services API for interacting with DocuSign.

<<<<<<< HEAD
OpenAPI spec version: v2.1
=======
OpenAPI spec version: v2
>>>>>>> 21be361feb7dcf8e34f4d3df2412dedff41c20d5
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

module DocuSign_eSign
<<<<<<< HEAD
  VERSION = "3.2.0.rc1"
=======
  VERSION = "3.0.0"
>>>>>>> 21be361feb7dcf8e34f4d3df2412dedff41c20d5
end
